/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atm;

/**
 *
 * @author Jesse
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jlAction = new javax.swing.JLabel();
        jtfPIin = new javax.swing.JTextField();
        jbtOne = new javax.swing.JButton();
        jbtTwo = new javax.swing.JButton();
        jbtThree = new javax.swing.JButton();
        jbtFour = new javax.swing.JButton();
        jbtFive = new javax.swing.JButton();
        jbtSix = new javax.swing.JButton();
        jbtSeven = new javax.swing.JButton();
        jbtEight = new javax.swing.JButton();
        jbtNine = new javax.swing.JButton();
        jbtClear = new javax.swing.JButton();
        jbtConfirm = new javax.swing.JButton();
        jbtZero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(0, 102, 0));
        jlTitle.setText("ATM");

        jlAction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlAction.setText("Please enter your PIN number:");

        jtfPIin.setEditable(false);
        jtfPIin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfPIin.setText("0000");
        jtfPIin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPIinActionPerformed(evt);
            }
        });

        jbtOne.setText("1");
        jbtOne.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtOne.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtOne.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtTwo.setText("2");
        jbtTwo.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtTwo.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtTwo.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtThree.setText("3");
        jbtThree.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtThree.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtThree.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtFour.setText("4");
        jbtFour.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtFour.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtFour.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtFive.setText("5");
        jbtFive.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtFive.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtFive.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtSix.setText("6");
        jbtSix.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtSix.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtSix.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtSeven.setText("7");
        jbtSeven.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtSeven.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtSeven.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtEight.setText("8");
        jbtEight.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtEight.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtEight.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtNine.setText("9");
        jbtNine.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtNine.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtNine.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtClear.setText("c");
        jbtClear.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtClear.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtClear.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtConfirm.setText("*");
        jbtConfirm.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtConfirm.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtConfirm.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtZero.setText("0");
        jbtZero.setMaximumSize(new java.awt.Dimension(50, 50));
        jbtZero.setMinimumSize(new java.awt.Dimension(50, 50));
        jbtZero.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jlTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlAction))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtZero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtFour, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtFive, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtSix, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtOne, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtThree, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtEight, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtNine, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jtfPIin, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAction)
                .addGap(18, 18, 18)
                .addComponent(jtfPIin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtOne, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtThree, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtFour, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtFive, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSix, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtEight, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtNine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtZero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPIinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPIinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPIinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtClear;
    private javax.swing.JButton jbtConfirm;
    private javax.swing.JButton jbtEight;
    private javax.swing.JButton jbtFive;
    private javax.swing.JButton jbtFour;
    private javax.swing.JButton jbtNine;
    private javax.swing.JButton jbtOne;
    private javax.swing.JButton jbtSeven;
    private javax.swing.JButton jbtSix;
    private javax.swing.JButton jbtThree;
    private javax.swing.JButton jbtTwo;
    private javax.swing.JButton jbtZero;
    private javax.swing.JLabel jlAction;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTextField jtfPIin;
    // End of variables declaration//GEN-END:variables
}
