/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atm;

/**
 *
 * @author Jesse
 */
public class SelectAccountScreen extends javax.swing.JFrame {

    private String action;
    
    /**
     * Creates new form SelectAccountScreen
     */
    public SelectAccountScreen(String actionType) {
        initComponents();
        
        action = actionType;
        
        if (action.equals(ATM.TRANSACTION_TRANSFER))
        {
            jlAction.setText("Please select an account to transfer FROM:");
        }
    }
    
    /**
     * Choose which screen to redirect to based on the user's choice of action.
     * @param acct 
     */
    private void chooseAction(String acct)
    {
        switch (action)
        {
            case ATM.TRANSACTION_DEPOSIT:
            case ATM.TRANSACTION_WITHDRAW:
            case ATM.TRANSACTION_TRANSFER:
                this.dispose();
                new TransactionScreen(acct,action).setVisible(true);  
                break;
            case ATM.TRANSACTION_INQUIRY:
                this.dispose();
                new InquiryScreen(acct,action).setVisible(true);  
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlAction = new javax.swing.JLabel();
        jbtChecking = new javax.swing.JButton();
        jbtSavings = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("ATM");

        jlAction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlAction.setText("Please select an account:");

        jbtChecking.setBackground(new java.awt.Color(0, 153, 51));
        jbtChecking.setText("Checking");
        jbtChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCheckingActionPerformed(evt);
            }
        });

        jbtSavings.setBackground(new java.awt.Color(0, 153, 51));
        jbtSavings.setText("Savings");
        jbtSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSavingsActionPerformed(evt);
            }
        });

        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jbtSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAction)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAction)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCheckingActionPerformed
        chooseAction("Checking");
    }//GEN-LAST:event_jbtCheckingActionPerformed

    private void jbtSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSavingsActionPerformed
        chooseAction("Savings");
    }//GEN-LAST:event_jbtSavingsActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_jbtCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtChecking;
    private javax.swing.JButton jbtSavings;
    private javax.swing.JLabel jlAction;
    // End of variables declaration//GEN-END:variables
}
