/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atm;

import javax.swing.JOptionPane;

/**
 *
 * @author Jesse
 */
public class TransactionScreen extends javax.swing.JFrame {

    private String account;
    private String action;
    
    /**
     * Creates new form TransactionScreen
     */
    public TransactionScreen(String acct, String act) {
        initComponents();
        
        account = acct;
        action = act;
        
        setCommandText();
    }
    
    private void setCommandText()
    {
        switch (action)
        {
            case ATM.TRANSACTION_DEPOSIT:
                jlAction.setText("Please enter the amount you want to deposit into your "+account+" account:");
                break;
            case ATM.TRANSACTION_WITHDRAW:
                jlAction.setText("Please enter the amount you want to withdraw from your "+account+" account:");
                break;
            case ATM.TRANSACTION_TRANSFER:                
                String otherAccount = account.equals(ATM.ACCOUNT_CHECKING) ? ATM.ACCOUNT_SAVINGS : ATM.ACCOUNT_CHECKING;                
                jlAction.setText("Please enter the amount you want to transfer to your "+otherAccount+" account:");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jlAction = new javax.swing.JLabel();
        jtfAmount = new javax.swing.JTextField();
        jbtCancel = new javax.swing.JButton();
        jbtOk = new javax.swing.JButton();
        jlDollarSign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(0, 102, 0));
        jlTitle.setText("ATM");

        jlAction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlAction.setText("Please enter the amount you want to deposit:");

        jtfAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfAmount.setText("100");
        jtfAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAmountActionPerformed(evt);
            }
        });

        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jbtOk.setText("Ok");
        jbtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOkActionPerformed(evt);
            }
        });

        jlDollarSign.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlDollarSign.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(jlTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlAction))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlDollarSign)
                                .addGap(6, 6, 6)
                                .addComponent(jtfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAction)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDollarSign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAmountActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOkActionPerformed
        
        JOptionPane.showMessageDialog(jtfAmount, "Your transaction was completed successfully!");
        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_jbtOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtOk;
    private javax.swing.JLabel jlAction;
    private javax.swing.JLabel jlDollarSign;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTextField jtfAmount;
    // End of variables declaration//GEN-END:variables
}
